### ISSUE TITLE
Console Output: Yo

### ISSUE THREAD

**Issue by ozzi-** [SAMLRaider/SAMLRaider#14]
Since i added SAMLRaider to Burp 1.6 i get a Yo output on the console every other hour or so.
I couldn't find the string in the project itself, so i may be mistaken.
Screenshot related.
![image](https://cloud.githubusercontent.com/assets/7944573/19432300/5ae67782-945c-11e6-8089-5e53da844f7e.png)

**Comment by nks0ne** [comment]
Having the same.

**Comment by lindi2** [comment]
This comes from org.fife.ui.rtextarea.RTextAreaBase

```
public void addNotify() {
    super.addNotify();
    if (this.getCaretPosition() != 0) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                System.out.println("Yo");
                RTextAreaBase.this.possiblyUpdateCurrentLineHighlightLocation();
            }
        });
    }
}
```

It has been fixed in https://github.com/bobbylight/RSyntaxTextArea/commit/5152e5b0e51729152abde2947442a4b5746a52cf which is part of 2.5.7.

**Comment by mindfuckup** [comment]
Thanks. So this will be fixed in the next release.

**Comment by mindfuckup** [comment]
Yeah \o/, sure it is alive! 😃

I have not much time to work on the project, but maybe in 2019 I find some time to implement some new features that are requested in the issues.

I'm very thankful for everyone that contributes and I'm already curious for your PRs ;-).

**Comment by lindi2** [comment]
Heh, that's the usual story. I also don't have much time to help but I pushed some patches to https://github.com/lindi2/SAMLRaider/commits/master that you might want to check out. I can create separate branches and pull requests of the ones that you like. (I have bad experiences with spending time to create pull requests that never get accepted because the project is just not maintained...)

**Comment by mindfuckup** [comment]
Resolved in release https://github.com/SAMLRaider/SAMLRaider/releases/tag/v1.2.3
