### ISSUE TITLE
Resigning message with cloned cert removes signature and certificate completely

### ISSUE THREAD

**Issue by egilas** [SAMLRaider/SAMLRaider#19]
Hi,

Love this extension! So here's the scenario: I've got a SAMLResponse that's being forwarded to target server, and I want to resign this response using my cloned certificate to see if the server actually validates the response. I use SAMLRaider to clone the certificate and that works well. 

When using the "(Re-)Sign Message" the signature and certificate is removed from the request instead of replacing the existing signature, leaving me with a SAML response that has neither a certificate nor a signature. Running burp 1.7.23 on windows 10 x64, using the extension from bapp store.

See illustrations:

Before using the "(Re-)Sign Message" functionality:
![illustration1](https://user-images.githubusercontent.com/14824771/26921440-5636f0b6-4c3c-11e7-975c-9efade709fc5.png)

After using it (sensitive fields in SAMLResponse grayed out):
![illustration2](https://user-images.githubusercontent.com/14824771/26921441-563906da-4c3c-11e7-81bd-5eb99d16dca4.png)

**Comment by mindfuckup** [comment]
Hi @egilas 

Do you still have this problem? Do you have this problem with all SAML Messages? Is the whole SAML Message or only the SAML Assertion signed in it's original state? Can you provide me such a SAML Message so that I can reproduce it (you can replace the sensitive content with something else)?

Best regards,
Emanuel

**Comment by mindfuckup** [comment]
I did not get an answer for further investigations. I'll close the issue.
