### ISSUE TITLE
Not working after getting response & test script error

### ISSUE THREAD

**Issue by misterch0c** [SAMLRaider/SAMLRaider#6]
I just cloned the repo and tried to use the script:

```
me@arch{~/pen/tools/SAMLRaider/scripts/samltest}:./samltest 
[*] Listening for SAML Response on port 23523...
[*] Sending SAML Response...
-:1: parser error : Document is empty

^
-:1: parser error : Start tag expected, '<' not found

^
```

I also tried from Kali and got the same output + "this is not an option" on the awk line.
After that I gave up and used only curl instead:
`curl -s --proxy 127.0.0.1:8080 --data saml_response "http://localhost:23523/" `

The thing is I cannot do anything. I've tried this test script because I have this issue with all SAML response. It will switch to the SAML  Raider tab when I get a SAMLResponse but I can't do anything:

![notwerking](https://i.imgur.com/lFZz0tw.png)

**Comment by mindfuckup** [comment]
Hi,

Thanks for testing SAML Raider and for your feedback.

* The first system you testet was an Arch Linux system?
* Which version of netcat (`nc`) are you using?

I think I know where the error comes from. I use the OpenBSD version of netcat (Package `community/openbsd-netcat` in Arch Linux and `netcat-openbsd` in Debian and also Kali i assume). 

When I use the GNU netcat, i got the same error as you got. In both Debian and Arch Linux. I was not able to identify the different behaviour in these tools but i could reproduce the error using GNU netcat.

Can you test the script with the OpenBSD version of netcat to confirm? Is the SAML Raider tab then showing the right things?

Thanks,
Mindfuckup

**Comment by misterch0c** [comment]
Hi, thx for helping!

I indeed tried in Arch but it's the same in Kali. So I've installed netcat-openbsd in Kali:

```
root@kali:~/SAMLRaider/scripts/samltest# nc -h
OpenBSD netcat (Debian patchlevel 1.105-7)
```

But I still get this:
```
root@kali:~/SAMLRaider/scripts/samltest# ./samltest 
[*] Listening for SAML Response on port 23523...
[*] Sending SAML Response...
awk: not an option: -niord
-:1: parser error : Document is empty

^
-:1: parser error : Start tag expected, '<' not found

^
^C

```

I don't really care about the test script honestly, the curl cmd I posted in my first post should do the trick right? My real problem is is that I can't choose any option in the attack tab for some reason (still in Kali).

**Comment by mindfuckup** [comment]
Hi

Ah, now I understand correctly.

Which version are you using? The version from the BApp Store, the JAR from the GitHub Release or a self-built one? I'll try it out on Kali this week if I get time to do it.

Thanks

**Comment by mindfuckup** [comment]
Hey, I have news :)

### Used Linux Distribution

I tested it on Kali Linux on a live usb drive:

    root@kali:~# cat /etc/lsb-release 
    DISTRIB_ID=Kali
    DISTRIB_RELEASE=2.0
    DISTRIB_CODENAME=sana
    DISTRIB_DESCRIPTION="Kali GNU/Linux 2.0"
    root@kali:~# uname -a
    Linux kali 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux

### Get the `samltest` script working

To use the `samltest` script, the following software must be installed:

* Package `netcat-openbsd` which provides `nc`. Otherwise, it's not correctly listening in the background.
* Package `gawk` (GNU awk) wich provides `awk`. Otherwise, some options used in the script are not available. You have to set as default for `awk`

I performed these steps:

    root@kali:~# apt-get install gawk
    root@kali:~# apt-get install netcat-openbsd
    root@kali:~# update-alternatives --set nc /bin/nc.openbsd # this is done by default wen netcat-openbsd is installed
    root@kali:~# update-alternatives --set awk /usr/bin/gawk # this has to be done manually

### Get SAML Raider working

#### Installing using BApp store

I got some graphical issues installing the extension: In the `Extender` Tab under `BApp Store`, the Extensions are not listed correctly. It's very difficult to select and install an extension. I had to resize the window several times so the GUI was redrawn correct again. After some fiddling around, it worked to install the extension.

#### Installing using our release:

I downloaded our release jar file and installed it manually inside Burp using the `Extender` → `Extensions` → `Add` function. This worked like expected.

#### Using the extension

The extension worked like expected: After executing `./samltest` or `curl -s --proxy 127.0.0.1:8080 --data @saml_response http://localhost:2323` I was able to click on the `SAML Raider` tab to edit the SAML Assertion:

![screenshot from 2015-11-10 20 56 40](https://cloud.githubusercontent.com/assets/438188/11075560/971772aa-87ed-11e5-8596-8863faf1a353.png)

#### Still not working?

So if you don't see the `SAML Raider` Tab, when you get an SAML Assertion, I have another question: Is the Tab `SAML Raider Certificates` in the top right corner working?

If not i think the Extension is not installed properly. Do you see any errors while installing the extension? Can you test it on a clean Kali box again and reproduce the steps?


Thanks, 

Mindfuckup
